name : module1

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # module1

  test :
    uses : SRetip/test_sys/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/module1/Cargo.toml'
      module_path: 'module/module1/'
      module_name : 'module1'
      commit_message : ${{ github.event.head_commit.message }}
