name : example_module

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # example_module

  test :
    uses : SRetip/test_sys/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/module1/'
      module_name : 'example_module'
      commit_message : ${{ github.event.head_commit.message }}
