name : example_module

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # example_module

  test :
    uses : Username/TestProject/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/module1/Cargo.toml'
      module_name : 'example_module'
      commit_message : ${{ github.event.head_commit.message }}
